### ISSUE TITLE
Option to disable a system

### ISSUE THREAD

**Issue by fabslab** [redxdev/ECS#10] opened 2018-09-14 04:43 UTC
I'd like to disable certain systems from running based on certain game events. To support would require being able to get a system from the world and call a method or set a field to disable it. Systems that are disabled would not have their tick methods called until reenabled.

**Comment by MachineMitch21** [comment] 2018-09-14 11:34
I just added some quick Enable and Disable methods to the world class.  This requires that another vector of systems be stored in the world, though.  But it would allow for Enabling and Disabling to happen once and there wouldn't be any redirection in the world's tick method having to check a flag to see if a system is disabled or not.  I did test this on the sample program and it did work as intended.

        'void EnableSystem(EntitySystem* system)
        {
            auto it = std::find(disabledSystems.begin(), disabledSystems.end(), system);
            if (it != disabledSystems.end())
            {
                disabledSystems.erase(it);
                systems.push_back(system);
            }
        }

        void DisableSystem(EntitySystem* system)
        {
            auto it = std::find(systems.begin(), systems.end(), system);
            if (it != systems.end())
            {
                systems.erase(it);
                disabledSystems.push_back(system);
            }
        }`

**Comment by MachineMitch21** [comment] 2018-09-14 11:41
Oh, I forgot to add that I also had RegisterSystem return an EntitySystem* to the system that was just added so that you could have this syntax if you wanted to keep a pointer to a system.

        EntitySystem* system = world->registerSystem(new TestSystem());

        world->EnableSystem(system);
        world->DisableSystem(system);

**Comment by redxdev** [comment] 2018-09-14 20:20
Closed via #11

**Closed as completed by redxdev** 2018-09-14 20:20 UTC
